'use client'

import { useState } from 'react'
import { motion } from 'framer-motion'
import { Bot, ArrowLeft, AlertTriangle, CheckCircle } from 'lucide-react'
import Link from 'next/link'
import { toast } from 'sonner'
import FileDropzone from '@/components/ui/FileDropzone'
import Button from '@/components/ui/Button'
import { useFileStore } from '@/lib/store'
import { imageApi } from '@/lib/api'

export default function AICheckerPage() {
    const { files, clearFiles } = useFileStore()
    const [isProcessing, setIsProcessing] = useState(false)
    const [results, setResults] = useState<Array<{ original: string; ai_probability: number; analysis: Record<string, number> }>>([])

    const handleCheck = async () => {
        if (files.length === 0) {
            toast.error('Please add at least one image')
            return
        }
        setIsProcessing(true)
        setResults([])
        try {
            const response = await imageApi.aiCheck(files.map((f) => f.file))
            if (response.data.success) {
                setResults(response.data.results)
                toast.success('Analysis complete!')
            }
        } catch (error: unknown) {
            toast.error(error instanceof Error ? error.message : 'Analysis failed')
        } finally {
            setIsProcessing(false)
        }
    }

    const getProbabilityColor = (prob: number) => {
        if (prob >= 70) return 'text-red-400'
        if (prob >= 40) return 'text-yellow-400'
        return 'text-green-400'
    }

    return (
        <div className="min-h-screen py-12">
            <div className="max-w-4xl mx-auto px-6">
                <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="mb-8">
                    <Link href="/images" className="inline-flex items-center gap-2 text-[var(--text-muted)] hover:text-[var(--text-primary)] mb-4 transition-colors">
                        <ArrowLeft className="w-4 h-4" /> Back to Image Tools
                    </Link>
                    <div className="flex items-center gap-4">
                        <div className="tool-card-icon w-14 h-14">
                            <Bot className="w-7 h-7 text-[var(--premium-blue-400)]" />
                        </div>
                        <div>
                            <h1 className="text-3xl font-bold">AI Image Checker</h1>
                            <p className="text-[var(--text-muted)]">Detect if an image was generated by AI</p>
                        </div>
                    </div>
                </motion.div>

                <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }} className="space-y-6">
                    <div className="glass-panel p-6">
                        <h2 className="text-lg font-semibold mb-4">Upload Images</h2>
                        <FileDropzone accept={{ 'image/*': ['.png', '.jpg', '.jpeg', '.webp'] }} />
                    </div>

                    <div className="glass-card p-4 border-yellow-500/30">
                        <p className="text-sm text-[var(--text-secondary)]">
                            ⚠️ <strong>Note:</strong> This uses basic heuristic analysis. For accurate AI detection, specialized ML models are required.
                        </p>
                    </div>

                    <Button variant="primary" size="lg" className="w-full" onClick={handleCheck} loading={isProcessing} disabled={files.length === 0}>
                        <Bot className="w-5 h-5" /> Analyze {files.length} Image{files.length !== 1 ? 's' : ''}
                    </Button>

                    {results.length > 0 && (
                        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="space-y-4">
                            {results.map((result, i) => (
                                <div key={i} className="glass-panel p-6">
                                    <div className="flex items-center justify-between mb-4">
                                        <span className="font-medium">{result.original}</span>
                                        <div className="flex items-center gap-2">
                                            {result.ai_probability >= 50 ? (
                                                <AlertTriangle className="w-5 h-5 text-yellow-400" />
                                            ) : (
                                                <CheckCircle className="w-5 h-5 text-green-400" />
                                            )}
                                            <span className={`text-2xl font-bold ${getProbabilityColor(result.ai_probability)}`}>
                                                {result.ai_probability}%
                                            </span>
                                        </div>
                                    </div>
                                    <div className="w-full bg-[var(--black-surface)] rounded-full h-3 mb-4">
                                        <div className={`h-3 rounded-full ${result.ai_probability >= 70 ? 'bg-red-500' : result.ai_probability >= 40 ? 'bg-yellow-500' : 'bg-green-500'}`} style={{ width: `${result.ai_probability}%` }} />
                                    </div>
                                    <div className="grid grid-cols-3 gap-4 text-sm">
                                        <div className="text-center p-3 rounded-lg bg-[var(--glass-white)]">
                                            <p className="text-[var(--text-muted)]">Noise</p>
                                            <p className="font-medium">{result.analysis.noise_level?.toFixed(1)}</p>
                                        </div>
                                        <div className="text-center p-3 rounded-lg bg-[var(--glass-white)]">
                                            <p className="text-[var(--text-muted)]">Edges</p>
                                            <p className="font-medium">{(result.analysis.edge_density * 100)?.toFixed(1)}%</p>
                                        </div>
                                        <div className="text-center p-3 rounded-lg bg-[var(--glass-white)]">
                                            <p className="text-[var(--text-muted)]">Color Var</p>
                                            <p className="font-medium">{result.analysis.color_uniformity?.toFixed(1)}</p>
                                        </div>
                                    </div>
                                </div>
                            ))}
                            <Button variant="ghost" className="w-full" onClick={() => { clearFiles(); setResults([]); }}>Check More Images</Button>
                        </motion.div>
                    )}
                </motion.div>
            </div>
        </div>
    )
}
