'use client'

import { useState } from 'react'
import { motion } from 'framer-motion'
import { Bot, ArrowLeft, AlertTriangle, CheckCircle } from 'lucide-react'
import Link from 'next/link'
import { toast } from 'sonner'
import FileDropzone from '@/components/ui/FileDropzone'
import Button from '@/components/ui/Button'
import { useFileStore } from '@/lib/store'
import { videoApi } from '@/lib/api'

export default function VideoAIIdentifierPage() {
    const { files, clearFiles } = useFileStore()
    const [isProcessing, setIsProcessing] = useState(false)
    const [results, setResults] = useState<Array<{ original: string; ai_probability: number; analysis: Record<string, unknown> }>>([])

    const handleCheck = async () => {
        if (files.length === 0) {
            toast.error('Please add at least one video')
            return
        }
        setIsProcessing(true)
        setResults([])
        try {
            const response = await videoApi.aiIdentify(files.map((f) => f.file))
            if (response.data.success) {
                setResults(response.data.results)
                toast.success('Analysis complete!')
            }
        } catch (error: unknown) {
            toast.error(error instanceof Error ? error.message : 'Analysis failed')
        } finally {
            setIsProcessing(false)
        }
    }

    return (
        <div className="min-h-screen py-12">
            <div className="max-w-4xl mx-auto px-6">
                <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="mb-8">
                    <Link href="/videos" className="inline-flex items-center gap-2 text-[var(--text-muted)] hover:text-[var(--text-primary)] mb-4 transition-colors">
                        <ArrowLeft className="w-4 h-4" /> Back to Video Tools
                    </Link>
                    <div className="flex items-center gap-4">
                        <div className="tool-card-icon w-14 h-14">
                            <Bot className="w-7 h-7 text-[var(--premium-blue-400)]" />
                        </div>
                        <div>
                            <h1 className="text-3xl font-bold">AI Video Identifier</h1>
                            <p className="text-[var(--text-muted)]">Detect if a video was generated by AI</p>
                        </div>
                    </div>
                </motion.div>

                <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }} className="space-y-6">
                    <div className="glass-panel p-6">
                        <h2 className="text-lg font-semibold mb-4">Upload Videos</h2>
                        <FileDropzone accept={{ 'video/*': ['.mp4', '.avi', '.mkv', '.mov', '.webm'] }} />
                    </div>

                    <div className="glass-card p-4 border-yellow-500/30">
                        <p className="text-sm text-[var(--text-secondary)]">
                            ⚠️ <strong>Note:</strong> Video AI detection requires specialized ML models. This provides basic metadata analysis only.
                        </p>
                    </div>

                    <Button variant="primary" size="lg" className="w-full" onClick={handleCheck} loading={isProcessing} disabled={files.length === 0}>
                        <Bot className="w-5 h-5" /> Analyze Video{files.length > 1 ? 's' : ''}
                    </Button>

                    {results.length > 0 && (
                        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="space-y-4">
                            {results.map((result, i) => (
                                <div key={i} className="glass-panel p-6">
                                    <div className="flex items-center justify-between mb-4">
                                        <span className="font-medium">{result.original}</span>
                                        <div className="flex items-center gap-2">
                                            {result.ai_probability >= 50 ? <AlertTriangle className="w-5 h-5 text-yellow-400" /> : <CheckCircle className="w-5 h-5 text-green-400" />}
                                            <span className="text-2xl font-bold">{result.ai_probability}%</span>
                                        </div>
                                    </div>
                                    <div className="grid grid-cols-2 md:grid-cols-4 gap-4 text-sm">
                                        <div className="text-center p-3 rounded-lg bg-[var(--glass-white)]">
                                            <p className="text-[var(--text-muted)]">Codec</p>
                                            <p className="font-medium">{String(result.analysis.codec || 'N/A')}</p>
                                        </div>
                                        <div className="text-center p-3 rounded-lg bg-[var(--glass-white)]">
                                            <p className="text-[var(--text-muted)]">Resolution</p>
                                            <p className="font-medium">{String(result.analysis.resolution || 'N/A')}</p>
                                        </div>
                                        <div className="text-center p-3 rounded-lg bg-[var(--glass-white)]">
                                            <p className="text-[var(--text-muted)]">Duration</p>
                                            <p className="font-medium">{Number(result.analysis.duration || 0).toFixed(1)}s</p>
                                        </div>
                                        <div className="text-center p-3 rounded-lg bg-[var(--glass-white)]">
                                            <p className="text-[var(--text-muted)]">Bitrate</p>
                                            <p className="font-medium">{Math.round(Number(result.analysis.bitrate || 0) / 1000)}kbps</p>
                                        </div>
                                    </div>
                                </div>
                            ))}
                            <Button variant="ghost" className="w-full" onClick={() => { clearFiles(); setResults([]); }}>Check More Videos</Button>
                        </motion.div>
                    )}
                </motion.div>
            </div>
        </div>
    )
}
