'use client'

import Link from 'next/link'
import { motion } from 'framer-motion'
import {
    Image,
    RefreshCw,
    Crop,
    Eraser,
    Maximize2,
    Move,
    User,
    LayoutGrid,
    Palette,
    ScanText,
    Bot,
    FileImage
} from 'lucide-react'

const tools = [
    {
        id: 'converter',
        title: 'Format Converter',
        description: 'Convert images between PNG, JPG, WebP, GIF, BMP, TIFF formats',
        icon: RefreshCw,
        href: '/images/converter',
    },
    {
        id: 'to-pdf',
        title: 'Image to PDF',
        description: 'Convert single or multiple images into a PDF document',
        icon: FileImage,
        href: '/images/to-pdf',
    },
    {
        id: 'cropper',
        title: 'Image Cropper',
        description: 'Crop images with precision using custom dimensions',
        icon: Crop,
        href: '/images/cropper',
    },
    {
        id: 'background-remover',
        title: 'Background Remover',
        description: 'AI-powered background removal for any image',
        icon: Eraser,
        href: '/images/background-remover',
    },
    {
        id: 'upscaler',
        title: 'Image Upscaler',
        description: 'Upscale images 2x, 4x, or 8x with AI enhancement',
        icon: Maximize2,
        href: '/images/upscaler',
    },
    {
        id: 'resizer',
        title: 'Size Changer',
        description: 'Resize images to custom dimensions',
        icon: Move,
        href: '/images/resizer',
    },
    {
        id: 'passport',
        title: 'Passport Photo',
        description: 'Create passport-sized photos for any country',
        icon: User,
        href: '/images/passport',
    },
    {
        id: 'collage',
        title: 'Collage Maker',
        description: 'Create beautiful photo collages with multiple layouts',
        icon: LayoutGrid,
        href: '/images/collage',
    },
    {
        id: 'filters',
        title: 'Image Filters',
        description: 'Apply artistic filters and effects to images',
        icon: Palette,
        href: '/images/filters',
    },
    {
        id: 'ocr',
        title: 'OCR Scanner',
        description: 'Extract text from images using optical character recognition',
        icon: ScanText,
        href: '/images/ocr',
    },
    {
        id: 'ai-checker',
        title: 'AI Image Checker',
        description: 'Detect if an image was generated by AI',
        icon: Bot,
        href: '/images/ai-checker',
    },
]

export default function ImagesPage() {
    return (
        <div className="min-h-screen py-12">
            <div className="max-w-7xl mx-auto px-6">
                {/* Header */}
                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    className="mb-12"
                >
                    <div className="flex items-center gap-4 mb-4">
                        <div className="w-14 h-14 rounded-2xl bg-gradient-to-br from-blue-500 to-cyan-500 flex items-center justify-center">
                            <Image className="w-7 h-7 text-white" />
                        </div>
                        <div>
                            <h1 className="section-title text-3xl lg:text-4xl">Image Tools</h1>
                            <p className="text-[var(--text-muted)]">
                                Powerful tools to transform your images
                            </p>
                        </div>
                    </div>
                </motion.div>

                {/* Tools Grid */}
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                    {tools.map((tool, index) => (
                        <motion.div
                            key={tool.id}
                            initial={{ opacity: 0, y: 20 }}
                            animate={{ opacity: 1, y: 0 }}
                            transition={{ delay: index * 0.05 }}
                        >
                            <Link href={tool.href}>
                                <div className="tool-card h-full group">
                                    <div className="tool-card-icon">
                                        <tool.icon className="w-6 h-6 text-[var(--premium-blue-400)]" />
                                    </div>
                                    <h3 className="text-lg font-semibold mb-2 group-hover:text-[var(--premium-blue-400)] transition-colors">
                                        {tool.title}
                                    </h3>
                                    <p className="text-[var(--text-muted)] text-sm">
                                        {tool.description}
                                    </p>
                                </div>
                            </Link>
                        </motion.div>
                    ))}
                </div>
            </div>
        </div>
    )
}
