'use client'

import Link from 'next/link'
import { motion } from 'framer-motion'
import {
    Video,
    RefreshCw,
    Youtube,
    Instagram,
    Music,
    Film,
    Clapperboard,
    Bot
} from 'lucide-react'

const tools = [
    {
        id: 'converter',
        title: 'Format Converter',
        description: 'Convert videos between MP4, AVI, MKV, MOV, WebM formats',
        icon: RefreshCw,
        href: '/videos/converter',
    },
    {
        id: 'youtube',
        title: 'YouTube Downloader',
        description: 'Download videos from YouTube in best quality',
        icon: Youtube,
        href: '/videos/youtube',
    },
    {
        id: 'instagram',
        title: 'Instagram Downloader',
        description: 'Download videos and posts from Instagram',
        icon: Instagram,
        href: '/videos/instagram',
    },
    {
        id: 'shorts',
        title: 'Shorts Downloader',
        description: 'Download YouTube Shorts videos',
        icon: Film,
        href: '/videos/shorts',
    },
    {
        id: 'reels',
        title: 'Reels Downloader',
        description: 'Download Instagram Reels videos',
        icon: Clapperboard,
        href: '/videos/reels',
    },
    {
        id: 'extract-audio',
        title: 'Extract Audio',
        description: 'Extract audio track from any video file',
        icon: Music,
        href: '/videos/extract-audio',
    },
    {
        id: 'ai-identifier',
        title: 'AI Video Identifier',
        description: 'Detect if a video was generated by AI',
        icon: Bot,
        href: '/videos/ai-identifier',
    },
]

export default function VideosPage() {
    return (
        <div className="min-h-screen py-12">
            <div className="max-w-7xl mx-auto px-6">
                {/* Header */}
                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    className="mb-12"
                >
                    <div className="flex items-center gap-4 mb-4">
                        <div className="w-14 h-14 rounded-2xl bg-gradient-to-br from-purple-500 to-pink-500 flex items-center justify-center">
                            <Video className="w-7 h-7 text-white" />
                        </div>
                        <div>
                            <h1 className="section-title text-3xl lg:text-4xl">Video Tools</h1>
                            <p className="text-[var(--text-muted)]">
                                Download, convert, and edit your videos
                            </p>
                        </div>
                    </div>
                </motion.div>

                {/* Tools Grid */}
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                    {tools.map((tool, index) => (
                        <motion.div
                            key={tool.id}
                            initial={{ opacity: 0, y: 20 }}
                            animate={{ opacity: 1, y: 0 }}
                            transition={{ delay: index * 0.05 }}
                        >
                            <Link href={tool.href}>
                                <div className="tool-card h-full group">
                                    <div className="tool-card-icon">
                                        <tool.icon className="w-6 h-6 text-[var(--premium-blue-400)]" />
                                    </div>
                                    <h3 className="text-lg font-semibold mb-2 group-hover:text-[var(--premium-blue-400)] transition-colors">
                                        {tool.title}
                                    </h3>
                                    <p className="text-[var(--text-muted)] text-sm">
                                        {tool.description}
                                    </p>
                                </div>
                            </Link>
                        </motion.div>
                    ))}
                </div>
            </div>
        </div>
    )
}
